<!-- # Informed, Engaged, Responsible Community -->

## Grants Awarded

To date, TBERF has received $8.0M in funding + $13.3M in matching funds to support 80 grants within the Tampa Bay watershed.

Funded by sales from of the Tampa Bay Estuary Spelicaty License Plate, also known as the "Tarpon Tag", Bay Mini-Grants provide competative cash awards (up to $5,000) to community organizations for projects that help restore and protect Tampa Bay. To achieve Program CCMP goals, specific Bay Mini-Grant priority actions are annoucned annually. Expanding the use of green infrastructure and understanding emerging contaminants have both been recent Bay Mini-Grant priorities. Since 2000, sales from the Tarpon Tag speciality license plate have collectively awarded $2M to more than 370 community-based restoration projects in the bay through TBEP's Bay Mini-Grant program.

Established during the COVID-19 pandemic, the Digital Challenge Grant program was created to provide safer-at-home income opportunities for digital content creators, science communicators, graphic designers, and educators. In its first year, 10 creators were awarded more than $6k in project funding.
