<!-- # Informed, Engaged, Responsible Community -->

## Give-a-Day for the Bay

Community involvement has been at the center of Tampa Bay's recovery story since the start. Keeping that tradition alive is the Give-a-Day for the Bay volunteer program where community members put in "sweat equity" to protect and restore bay-area parks and preserves. From planting native vegetation to removing trash from a mangrove island, these events encourage the community to get out, give back, and enjoy the bay!

Since 2019, there have been 28 Give-A-Day for the Bay volunteer workdays co-hosted with 37 bay-area partners. During this time, significant attention has been given to addressing excessive litter and native habitat degradation in regions of the watershed that have historically not received support for restoration activities. During these events, 1,500 volunteers removed 5 tons of debris and litter, planted 5,680 native plants, and moved 30 tons of oyster shells to create oyster reefs. Volunteers have also participated in citizen science projects that highlighted the importance of blue carbon habitats by using tea bags to measure soil decomposition rates and carbon storage capacities of wetlands.
