<!-- # Clean Waters & Sediments -->

## Tidal Creeks

Tidal creeks or tributaries are essential habitats in the Tampa Bay estuary and are important focal points for understanding watershed inputs that affect water quality. A fundamental goal of the Tampa Bay Estuary Program is to develop effective nutrient management strategies to support the ecological function of tidal tributaries. In partnership with Sarasota Bay NEP, Coastal & Heartland NEP, and local government and agency stakeholders, a tidal creek assessment framework was developed to evaluate the environmental health of these valuable ecosystems. 

The tidal creek assessment framework supports tracking of water quality management goals and can help refine restoration and management plans in priority tributaries, including those in need of hydrologic restoration that can support critical nursery habitats for sportfishes.  Similar to the water quality report card, tidal creeks are assigned to different categories that describe current conditions and inform management actions that support protection or restoration of bay habitats.

Tidal creeks are assigned to one of five categories: Monitor: Creek is at or below nitrogen concentrations that protect individual creek types within the larger population of creeks. Caution: Creek nutrients showing signs of elevated nutrient concentrations that may increase risk of eutrophic condition. Investigate: Creek nutrient concentrations above margin of safety to protect creek from potential impairment. Prioritize: Creek nutrient concentrations have exceeded regulatory standard for associated freshwater portion of ghe tributary indicating that actions are needed to identify remediative measures to reduce nutrients in the creek. No Data: Insufficient data exist to assess tidal creeks condition, additional monitoring is needed.

The current assessment period (2021) indicates that nine creeks had a "Prioritize" score, ten had an "Investigate" score, nine had a "Caution" score, and 58 had a "Monitor" score.  The remaining 142 creeks in the Tampa Bay watershed had insufficient data for the current assessment period to assign a category. 

Link to tidal creeks data page: https://tbep.org/tidal-creeks/