library(knitr)
library(tbeptools)
library(dplyr)
library(tidyr)
library(tibble)
library(extrafont)
library(patchwork)
library(ggmap)
library(sf)
library(extrafont)
library(readxl)
library(ggfx)
library(grid)
library(here)
library(htmltools)
library(plotly)
library(reactable)
library(reactablefmtr)
library(googlesheets4)
library(googledrive)
library(emojifont)
library(stringr)
library(crosstalk)
library(leaflet)
library(DT)
library(lubridate)

drive_auth(email = 'mbeck@tbep.org')
gs4_auth(token = drive_token())

loadfonts(device = 'win', quiet = T)
fml <- "Lato"

source(here('R/funcs.R'))

knitr::opts_chunk$set(message = F, echo = F, warning = F, fig.align = 'center')
